AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image-replacer

  Sample SAM Template for image-replacer

Globals:
  Function:
    Timeout: 3

Resources:
  S3:
    Type: AWS::S3::Bucket
  RolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: imagereplacer-policy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              Fn::Join:
                - '/'
                -
                  - !GetAtt S3.Arn
                  - "*"
      Roles:
        - !Ref FunctionRole
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: ruby2.5
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: post
      Environment:
        Variables:
          BUCKET_NAME: !Ref S3
Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  Function:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt Function.Arn
  IamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FunctionRole.Arn
  S3Bucket:
    Value: !Ref S3
