on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8.0
      - run: pip install aws-sam-cli
      - name: sam build
        run: sam build --use-container
      - name: sam package
        run: sam package --output-template-file packaged.yaml --s3-bucket masarakki-sam-deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          SAM_CLI_TELEMETRY: 0
